[package]
name = "ezcrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"          # AES-GCM provides the high-level AEAD
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
argon2 = "0.4"
anyhow = "1.0"
blake3 = "1.3"